# Configuration file for golangci-lint
# For more options, see https://golangci-lint.run/usage/configuration/

version = "v2"

[linters]
default = "standard"
disabled = [
  "forbidigo", # forbids identifiers matched by reg exps
]
enable = [
  "asciicheck",
  "bodyclose",
  "copyloopvar",
  "cyclop",
  "durationcheck",
  "errcheck",
  "errorlint",
  "fatcontext",
  "gocritic",
  "gomoddirectives",
  "gomodguard",
  "gosec",
  "govet",
  "iface",
  "ineffassign",
  "intrange",
  "misspell",
  "nakedret",
  "nilerr",
  "noctx",
  "nolintlint",
  "perfsprint",
  "prealloc",
  "predeclared",
  "revive",
  "sqlclosecheck",
  "staticcheck",
  "testifylint",
  "testpackage",
  "unconvert",
  "unused",
  "wastedassign",
  "wrapcheck",
  "wsl",
]
relative-path-mode = "gomod"

[formatters]
enable = ["goimports"]

[linters.settings]

[linters.settings.revive]
enable-all-rules = true

[linters.settings.staticcheck]
checks = ["all"]

[linters.settings.testifylint]
enable-all = true
